development:
  adapter: postgresql
  database: empdir_development
  pool: 5
  timeout: 5000
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
test:
  adapter: postgresql
  database: empdir_test
  pool: 5
  timeout: 5000
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost

production:
  adapter: postgresql
  database: empdir_production
  pool: 5
  timeout: 5000