name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    rspec:
      name: Run RSpec tests
      runs-on: ubuntu-latest
      
      services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: api_rails_oneorder_test
          ports:
              - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          timeout-minutes: 2
        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with: 
              ruby-version: 3.2.3
        - name: Install dependencies
          run: bundle install
        - name: Run tests
          env:
            RAILS_ENV: test
            DATABASE_URL: postgres://postgres:postgres@localhost:5432
          run: |
            bundle exec rails db:create
            bundle exec rails db:migrate
            bundle exec rspec
    build-and-push:
      name: Build and push Docker image
      runs-on: ubuntu-latest
      needs: rspec
      steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/github-actions-demo:latest
            ${{ secrets.DOCKER_USERNAME }}/github-actions-demo:${{ github.ref_name }}
      
